// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGt5MRASVfilQS-C7h3f7OBHJZKNspW6A',
    appId: '1:1052333107123:web:aaac55426e2ace3a058dc6',
    messagingSenderId: '1052333107123',
    projectId: 'my-website-2f7f3',
    authDomain: 'my-website-2f7f3.firebaseapp.com',
    storageBucket: 'my-website-2f7f3.appspot.com',
    measurementId: 'G-P9916WZK0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc8VKs9e1Ddm9wdQ0lTbYOo1litBF0Tvk',
    appId: '1:1052333107123:android:585c73c7ead1c27d058dc6',
    messagingSenderId: '1052333107123',
    projectId: 'my-website-2f7f3',
    storageBucket: 'my-website-2f7f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAjuznVI_QSpuW18NGG89Tgl56ESskgj8',
    appId: '1:1052333107123:ios:d33ad119d56fa550058dc6',
    messagingSenderId: '1052333107123',
    projectId: 'my-website-2f7f3',
    storageBucket: 'my-website-2f7f3.appspot.com',
    iosClientId: '1052333107123-8frprdoe1gq5k52p4pei1h70dtt873oq.apps.googleusercontent.com',
    iosBundleId: 'myweb',
  );
}
