import 'package:flutter/material.dart';

const List<Text> updateNotes = [
  Text("02/22/2022", style: TextStyle(fontSize: 17),),
  Text("  - Added dice roller as a test app", style: TextStyle(fontSize: 13),),
  Text(""),
  Text("02/21/2022", style: TextStyle(fontSize: 17),),
  Text("  - UI update", style: TextStyle(fontSize: 13),),
  Text(""),
  Text("02/20/2022", style: TextStyle(fontSize: 17),),
  Text("  - Integrated Google login", style: TextStyle(fontSize: 13),),
  Text(""),
  Text("02/19/2022", style: TextStyle(fontSize: 17),),
  Text("  - Site layout update", style: TextStyle(fontSize: 13),),
  Text("  - Improved emoji page loading ", style: TextStyle(fontSize: 13),),
  Text(""),
  Text("01/17/2022", style: TextStyle(fontSize: 17),),
  Text("  - About Page format update", style: TextStyle(fontSize: 13),),
  Text(""),
  Text("01/08/2022", style: TextStyle(fontSize: 17),),
  Text("  - About Me", style: TextStyle(fontSize: 13),),
  Text(""),
  Text("12/25/2021", style: TextStyle(fontSize: 17),),
  Text("  - Emoji Wall", style: TextStyle(fontSize: 13),),
  Text(""),
  Text("12/23/2021", style: TextStyle(fontSize: 17),),
  Text("  - Dark mode", style: TextStyle(fontSize: 13),),
  Text("  - Adaptive layout", style: TextStyle(fontSize: 13),),
  Text(""),
  Text("12/22/2021", style: TextStyle(fontSize: 17),),
  Text("  - Website created", style: TextStyle(fontSize: 13),),
  Text(""),
];